CICD_PIPELINE

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -9,9 +9,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: ip add
-        run: ifconfig
-
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
@@ -34,3 +31,14 @@ jobs:
           sleep 3
           done
           echo "Frontend failed to start" && exit 1
+      - name: Wait for backend
+        run: |
+          for i in {1..15}; do
+          if curl -s http://localhost:8082 > /dev/null; then
+          echo "Backend is up!"
+          exit 0
+          fi
+          echo "Waiting for backend`..."
+          sleep 3
+          done
+          echo "Backend failed to start" && exit 1
